version: "3.9"
services:
  devenv:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - ../:/workdir
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.ssh:/home/user/.ssh
    dns:
      - 192.168.1.1
